packages:
  - client
  - server
  - shared
  - worker

settings:
  catalogMode: strict

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild

catalog:
  '@fontsource/inter': ^5.2.5
  '@fontsource/noto-sans': ^5.2.6
  '@types/better-sqlite3': ^7.6.11
  '@types/express': ^5.0.0
  '@types/ffprobe': ^1.1.8
  '@types/ffprobe-static': ^2.0.3
  '@types/node': ^24.0.15
  '@types/object-hash': ^3.0.6
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  '@typescript-eslint/eslint-plugin': ^8.26.1
  '@typescript-eslint/parser': ^8.26.1
  '@vitejs/plugin-react': ^4.3.4
  better-sqlite3: ^11.9.0
  bootstrap-icons: ^1.11.3
  chokidar: ^4.0.3
  compare-versions: ^6.1.1
  cors: ^2.8.5
  dotenv: ^16.4.5
  eslint: ^9.22.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.7
  express: ^4.21.1
  ffprobe: ^1.1.2
  ffprobe-static: ^3.1.0
  mime: ^4.0.4
  object-hash: ^3.0.0
  react: ^19.0.0
  react-dom: ^19.0.0
  react-router-dom: ^6.25.1
  sass: ^1.85.1
  socket.io: ^4.8.0
  socket.io-client: ^4.7.5
  tsconfig-paths: ^4.2.0
  tsx: ^4.16.2
  typescript: ^5.8.2
  vite: ^6.2.2
  vite-tsconfig-paths: ^5.1.3
  winston: ^3.14.2
  winston-daily-rotate-file: ^5.0.0
  yaml: ^2.4.5
