export const AudioEncoderLookup: { [index: string]: string } = {
	copy: 'Auto Passthru',
	'copy:aac': 'AAC Passthru',
	'copy:ac3': 'AC3 Passthru',
	'copy:eac3': 'E-AC3 Passthru',
	'copy:truehd': 'TrueHD Passthru',
	'copy:dts': 'DTS Passthru',
	'copy:dtshd': 'DTS-HD Passthru',
	'copy:mp2': 'MP2 Passthru',
	'copy:mp3': 'MP3 Passthru',
	'copy:flac': 'FLAC Passthru',
	'copy:opus': 'Opus Passthru',
	ac3: 'AC3',
	av_aac: 'AAC (avcodec)',
	eac3: 'E-AC3',
};

export const FilterLookup: { [index: string]: string } = {
	off: 'Off',
	none: 'None',
	default: 'Default',
	custom: 'Custom',
	ultralight: 'Ultralight',
	light: 'Light',
	medium: 'Medium',
	strong: 'Strong',
	stronger: 'Stronger',
	verystrong: 'Very Strong',
	ultrafine: 'Ultrafine',
	fine: 'Fine',
	coarse: 'Coarse',
	verycoarse: 'Very Coarse',
	tiny: 'Tiny',
	small: 'Small',
	large: 'Large',
	wide: 'Wide',
	verywide: 'Very Wide',
	yadif: 'Yadif',
	decomb: 'Decomb',
	'skip-spatial': 'Skip Spatial Check',
	bob: 'Bob',
	nlmeans: 'NLMeans',
	eedi2: 'EEDI2',
	eedi2bob: 'EEDI2 Bob',
	unsharp: 'UnSharp',
	lapsharp: 'LapSharp',
	bt2020: 'BT.2020',
	bt709: 'BT.709',
	'bt601-6-525': 'BT.601 SMPTE-C',
	'bt601-6-625': 'BT.601 EBU',
};
