export type GithubReleaseResponseType = {
	url: string;
	assets_url: string;
	upload_url: string;
	html_url: string;
	id: number;
	author: {};
	node_id: string;
	tag_name: string;
	target_commitish: string;
	name: string;
	draft: boolean;
	prerelease: boolean;
	created_at: string;
	published_at: string;
	assets: [];
	tarball_url: string;
	zipball_url: string;
	body: string;
	mentions_count: number;
};
