services:
  handbrake-server:
    image: thenickoftime/handbrake-web:latest
    container_name: handbrake-web-server
    environment:
      - HANDBRAKE_MODE=server
    ports:
      - 9999:9999
    volumes:
      - /path/to/your/data:/data
      - /path/to/your/media:/video

  handbrake-worker:
    image: thenickoftime/handbrake-web:latest
    container_name: handbrake-web-worker
    environment:
      - HANDBRAKE_MODE=worker
      - SERVER_URL=http://yourserver.url
      - SERVER_PORT=9999
    volumes:
      - /path/to/your/media:/video
    depends_on:
      - handbrake-server
