name: Build HandBrake

on:
  push:
    branches:
      - main
    paths:
      - handbrake/Dockerfile
  pull_request:
    branches:
      - main
    paths:
      - handbrake/Dockerfile

env:
  IMAGE: handbrake-build
  REGISTRY: ghcr.io
  REPO_OWNER: ${{ github.repository_owner }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  handbrake-build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        hardware-acceleration:
          - none
          - intel
          - nvidia

    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get HandBrake version
        run: cat handbrake/Dockerfile | grep -oP '(?<=ARG\s)(HANDBRAKE_VERSION=.+)' >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.IMAGE }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref_name == 'main' && matrix.hardware-acceleration == 'none' }}
            type=raw,value=${{ matrix.hardware-acceleration }},enable=${{ github.ref_name == 'main' && matrix.hardware-acceleration != 'none' }}
            type=raw,value=${{ env.HANDBRAKE_VERSION }},enable=${{ github.ref_name == 'main' && matrix.hardware-acceleration == 'none' }}
            type=raw,value=${{ env.HANDBRAKE_VERSION }}-${{ matrix.hardware-acceleration }},enable=${{ github.ref_name == 'main' && matrix.hardware-acceleration != 'none' }}
            type=raw,value=dev,enable=${{ github.ref_name != 'main' && matrix.hardware-acceleration == 'none' }}
            type=raw,value=dev-${{ matrix.hardware-acceleration }},enable=${{ github.ref_name != 'main' && matrix.hardware-acceleration != 'none' }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: 'handbrake/Dockerfile'
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          build-args: HARDWARE_ACCELERATION=${{matrix.hardware-acceleration}}
          provenance: false
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  handbrake-web-build:
    needs: handbrake-build
    uses: ./.github/workflows/docker-publish.yaml
