name: Build HandBrake

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/handbrake-build.yaml
      - handbrake/build.Dockerfile
      - handbrake/cli.Dockerfile
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/handbrake-build.yaml
      - handbrake/build.Dockerfile
      - handbrake/cli.Dockerfile

env:
  REGISTRY: ghcr.io
  REPO_OWNER: ${{ github.repository_owner }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  handbrake-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get HandBrake version
        run: cat handbrake/build.Dockerfile | grep -oP '(?<=ARG\s)(HANDBRAKE_VERSION=.+)' >> $GITHUB_ENV

  handbrake-build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/handbrake-build
          tags: |
            type=raw,value=latest,enable={{ is_default_branch }}
            type=raw,value=${{ env.HANDBRAKE_VERSION }},enable={{ is_default_branch }}
            type=raw,value=dev,enable={{ is_not_default_branch }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: 'handbrake/build.Dockerfile'
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          provenance: mode=max
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  handbrake-cli:
    runs-on: ubuntu-latest

    needs: handbrake-build

    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/handbrake-cli
          tags: |
            type=raw,value=latest,enable={{ is_default_branch }}
            type=raw,value=${{ env.HANDBRAKE_VERSION }},enable={{ is_default_branch }}
            type=raw,value=dev,enable={{ is_not_default_branch }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: 'handbrake/cli.Dockerfile'
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          provenance: mode=max
          push: true
          build-args: |
            DISTROLESS_VARIANT=${{ github.head_ref == '' && 'nonroot' || 'debug-nonroot' }}
            HANDBRAKE_BUILD_TAG=${{ github.event_name == 'pull_request' && 'dev' || 'latest'}}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
