name: Package Cleanup

on:
  workflow_run:
    workflows: [Docker Publish]
    types: [completed]
    # branches: [main]
  # push:
  #   paths:
  #     - '.github/workflows/package-cleanup.yaml'

jobs:
  cleanup-packages:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Cleanup Untagged 'handbrake-web' Packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'handbrake-web'
          package-type: 'container'
          delete-only-untagged-versions: true
      - name: Cleanup Untagged 'handbrake-web-server' Packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'handbrake-web-server'
          package-type: 'container'
          delete-only-untagged-versions: true
      - name: Cleanup Untagged 'handbrake-web-worker' Packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'handbrake-web-worker'
          package-type: 'container'
          delete-only-untagged-versions: true
      - name: Cleanup Non-SemVer 'handbrake-web' Packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'handbrake-web-worker'
          package-type: 'container'
          ignore-versions: '^v\d+\.\d+\.\d+$'
