name: Package Cleanup

on:
  # workflow_run:
  #   workflows: [Docker Publish]
  #   types: [completed]
  pull_request:
    types: [closed]
  push:
    paths:
      - '.github/workflows/package-cleanup.yaml'

jobs:
  cleanup-packages:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Clean Untagged Versions
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: handbrake-web handbrake-web-server handbrake-web-worker
          tag-selection: untagged
          cut-off: 0s
      - name: Clean 'sha256-*' Versions
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: handbrake-web handbrake-web-server handbrake-web-worker
          tag-selection: tagged
          image-tags: 'sha256-*'
          cut-off: 0s
      - name: Clean This PR's 'pr-*' Versions
        if: github.event_name == 'pull_request'
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: handbrake-web handbrake-web-server handbrake-web-worker
          tag-selection: tagged
          image-tags: 'pr-${{github.event.number}}'
          cut-off: 0s
      - name: Clean Old PR's 'pr-*' Versions
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: handbrake-web handbrake-web-server handbrake-web-worker
          tag-selection: tagged
          image-tags: 'pr-*'
          cut-off: 2w
