name: Package Cleanup

on:
  workflow_run:
    workflows: [Docker Publish]
    types: [completed]
    # branches: [main]
  push:
    paths:
      - '.github/workflows/package-cleanup.yaml'

jobs:
  cleanup-packages:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Clean Untagged Versions
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: handbrake-web
          tag-selection: untagged
          dryrun: true
      - name: Clean Non-SemVer Versions
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: handbrake-web
          tag-selection: tagged
          image-tags: '!v*.*.*'
          dryrun: true
